### PR TITLE
chore: update to build with rust 1.80

### PR DESCRIPTION
**Pull request by chenrui333**
seeing some time related failure 

```
error[E0282]: type annotations needed for `Box<_>`
  --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

```

has been addressed with 0.3.36, https://github.com/time-rs/time/issues/693

### CODE REVIEW

**Comment by quietvoid** [comment]
It builds fine here.
Am I missing something? The current lockfile is already on `time` `version = "0.3.36"`.

**Comment by chenrui333** [comment]
@quietvoid yeah, you are right, it got handled with https://github.com/quietvoid/dovi_tool/commit/03e41c49beb62fc74c360c9c8c47e494beb7e2fc. (I might be looking at something else)

While we are in here, any chance cutting a new release? Thanks!

**Comment by quietvoid** [comment]
Yeah I can make a new release this weekend.
